### PR TITLE
Fix import resources with provider default tags

### LINKED ISSUE #3311: Tags not read when importing with defaultTags
### What happened?

I set aws.Provider's defaultTags and then tried some imports. Some work, but some are failing as it claims that tags don't match in spite of tags being present.

For [AWS Backup Plans](https://www.pulumi.com/registry/packages/aws/api-docs/backup/plan/), calling `aws backup get-backup-plan` does not return tags ([doc](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/get-backup-plan.html)). To get tags, `aws backup list-tags` needs to be called ([doc](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/list-tags.html)). Even though I've set the tags on a backup plan, it won't import because it claims the tags are missing. Using the above commands, I can get the tags so they are set. Could the underlying code be failing to perform the extra step to get tags when importing?

I'm experiencing the same problem with [Backup Vaults](https://www.pulumi.com/registry/packages/aws/api-docs/backup/vault/) and [Roles](https://www.pulumi.com/registry/packages/aws/api-docs/iam/role/). For Vaults, `aws backup describe-backup-vault` ([doc](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/backup/describe-backup-vault.html)) doesn't return tags but again `aws backup list-tags` does. For Roles, `aws iam get-role` does return tags.

After experiencing this problem, I removed defaultTags but then had to remove the tags to allow the import to proceed.

### Example

To keep this simple, I'll just provide the vault

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const provider = new aws.Provider(
  'provider-us-east-1',
  {
    defaultTags: {
      tags: {
        'pulumi:project': pulumi.getProject(),
        'pulumi:stack': pulumi.getStack(),
      },
    },
    profile: 'aws',
    region: 'us-east-1',
  }
);

const vault = new aws.backup.Vault(
  'productionVault',
  {
    name: 'production',
  },
  {
    import: 'production',
    parent: provider,
    provider,
  }
);
```

### Output of `pulumi about`

```
CLI
Version      3.102.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.18.2
nodejs  unknown

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v16.15.0'
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #4030: Cannot import resources when provider has default tags
### Describe what happened

When an AWS provider instance has `defaultTags` configured, AWS resources cannot be imported into Pulumi state using `pulumi up` because of differences shown by pulumi in the imported resource tags.

### Sample program

```
$ cat requirements.txt
pulumi>=3.0.0,<4.0.0
pulumi-aws>=6.0.2,<7.0.0

$ cat Pulumi.yaml
name: pulumi-defaulttags-import-issue
runtime:
  name: python
  options:
    virtualenv: venv

$ cat __main__.py
import pulumi
import pulumi_aws

test_import = pulumi.Config().get_bool("test_import")

bucket_name = "pulumi-aws-defaulttags-import-issue"

provider = pulumi_aws.Provider(
    "aws",
    default_tags={
        "tags": {
            "Project": "x",
            "Environment": "dev",
            "CodeRepository": "infra",
        }
    } if test_import else None,
)
pulumi_aws.s3.BucketV2(
    bucket_name,
    bucket=bucket_name,
    tags={
        "Environment": "dev",
        "CodeRepository": "legacy-infra",
        "CreatedBy": "terraform",
    },
    opts=pulumi.ResourceOptions(
        import_=bucket_name if test_import else None,
        provider=provider,
        retain_on_delete=True,
    ),
)
```

### Log output

```
$  pulumi up --skip-preview --diff --yes
Updating (dev)

View Live: https://app.pulumi.com/vertexinc/pulumi-defaulttags-import-issue/dev/updates/1

+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:dev::pulumi-defaulttags-import-issue::pulumi:pulumi:Stack::pulumi-defaulttags-import-issue-dev]
    + pulumi:providers:aws: (create)
        [urn=urn:pulumi:dev::pulumi-defaulttags-import-issue::pulumi:providers:aws::aws]
        region                   : "eu-west-1"
        skipCredentialsValidation: "false"
        skipRegionValidation     : "true"
        version                  : "6.38.1"
    + aws:s3/bucketV2:BucketV2: (create)
        [urn=urn:pulumi:dev::pulumi-defaulttags-import-issue::aws:s3/bucketV2:BucketV2::pulumi-aws-defaulttags-import-issue]
        [provider=urn:pulumi:dev::pulumi-defaulttags-import-issue::pulumi:providers:aws::aws::62cf8761-74c4-457a-8a89-8ca618d75c13]
        bucket      : "pulumi-aws-defaulttags-import-issue"
        forceDestroy: false
        tags        : {
            CodeRepository: "legacy-infra"
            CreatedBy     : "terraform"
            Environment   : "dev"
        }
        tagsAll     : {
            CodeRepository: "legacy-infra"
            CreatedBy     : "terraform"
            Environment   : "dev"
        }
        --outputs:--
        arn                               : "arn:aws:s3:::pulumi-aws-defaulttags-import-issue"
        bucketDomainName                  : "pulumi-aws-defaulttags-import-issue.s3.amazonaws.com"
        bucketRegionalDomainName          : "pulumi-aws-defaulttags-import-issue.s3.eu-west-1.amazonaws.com"
        grants                            : [
            [0]: {
                id         : "9a5403758502b3f38cc2f3a3f1bc8089ed04e2f0cd916cee1eaf1e9c8d6f408e"
                permissions: [
                    [0]: "FULL_CONTROL"
                ]
                type       : "CanonicalUser"
                uri        : ""
            }
        ]
        hostedZoneId                      : "Z1BKCTXD74EZPE"
        id                                : "pulumi-aws-defaulttags-import-issue"
        objectLockEnabled                 : false
        region                            : "eu-west-1"
        requestPayer                      : "BucketOwner"
        serverSideEncryptionConfigurations: [
            [0]: {
                rules: [
                    [0]: {
                        applyServerSideEncryptionByDefaults: [
                            [0]: {
                                kmsMasterKeyId: ""
                                sseAlgorithm  : "AES256"
                            }
                        ]
                        bucketKeyEnabled                   : false
                    }
                ]
            }
        ]
        versionings                       : [
            [0]: {
                enabled  : false
                mfaDelete: false
            }
        ]
Resources:
    + 3 created

Duration: 9s

$  pulumi state delete 'urn:pulumi:dev::pulumi-defaulttags-import-issue::aws:s3/bucketV2:BucketV2::pulumi-aws-defaulttags-import-issue'
 warning: This command will edit your stack's state directly. Confirm? Yes
Resource deleted

$  pulumi config set test_import 'true'

$  pulumi up --skip-preview --diff --yes
Updating (dev)

View Live: https://app.pulumi.com/vertexinc/pulumi-defaulttags-import-issue/dev/updates/3

  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::pulumi-defaulttags-import-issue::pulumi:pulumi:Stack::pulumi-defaulttags-import-issue-dev]
    ~ pulumi:providers:aws: (update)
        [id=62cf8761-74c4-457a-8a89-8ca618d75c13]
        [urn=urn:pulumi:dev::pulumi-defaulttags-import-issue::pulumi:providers:aws::aws]
      + defaultTags: (json) {
          + tags: {
              + CodeRepository: "infra"
              + Environment   : "dev"
              + Project       : "x"
            }
        }

error: inputs to import do not match the existing resource
error: update failed
Resources:
    ~ 1 updated
    1 unchanged

Duration: 6s
```

### Affected Resource(s)

_No response_

### Output of `pulumi about`

```
➜  pulumi about                     
CLI          
Version      3.118.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.38.1
language  python  unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in python: executable='/private/tmp/pulumi-defaulttags-import-issue/venv/bin/python3' version='3.12.3'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/piotr-bzdyl-vertexinc
User           piotr-bzdyl-vertexinc
Organizations  piotr-bzdyl-vertexinc, vertexinc
Token type     personal

Dependencies:
NAME        VERSION
pip         24.0
pulumi_aws  6.38.1

Pulumi locates its logs in /var/folders/pn/x8n_ksvj47128283fbf4fsqm0000gq/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #4080: Refresh shows permanent diff for tagsAll in pulumi@3.120.0
### Describe what happened

With the new refresh logic in pulumi@3.120.0 some resources have a permanent diff on `tagsAll` when that is not provided.

This is causing some of our tests to fail 
https://github.com/pulumi/pulumi-aws/actions/runs/9510947700/job/26232303592?pr=4077

### Sample program

```yaml
name: test-aws-1655-pf
runtime: yaml
description: |
    Initial deployment without tags
outputs:
    actual: ${res.tags}
resources:
    app:
        properties:
            name: pf-tags-test-app
        type: aws:appconfig:Application
    aws-provider:
        type: pulumi:providers:aws
    res:
        options:
            provider: ${aws-provider}
        properties:
            applicationId: ${app.id}
            name: pf-tags-test
        type: aws:appconfig:Environment

```

### Log output

grpc logs

```json
{
  "method": "/pulumirpc.ResourceProvider/Diff",
  "request": {
    "id": "e2suou4:3u5gdcd",
    "urn": "urn:pulumi:dev::test-aws-1655-pf::aws:appconfig/environment:Environment::res",
    "olds": {
      "applicationId": "3u5gdcd",
      "arn": "arn:aws:appconfig:us-east-2:123456789012:application/3u5gdcd/environment/e2suou4",
      "description": "",
      "environmentId": "e2suou4",
      "id": "e2suou4:3u5gdcd",
      "monitors": [],
      "name": "pf-tags-test",
      "state": "ReadyForDeployment",
      "tagsAll": {}
    },
    "news": {
      "applicationId": "3u5gdcd",
      "name": "pf-tags-test"
    },
    "oldInputs": {
      "applicationId": "3u5gdcd",
      "name": "pf-tags-test"
    }
  },
  "response": {
    "changes": "DIFF_SOME",
    "diffs": [
      "tagsAll"
    ]
  },
  "metadata": {
    "kind": "resource",
    "mode": "client",
    "name": "aws"
  }
}
```

CLI output

```console
Previewing refresh (dev)

View in Browser (Ctrl+O): https://app.pulumi.com/chall-pulumi-corp/test-aws-1655-pf/dev/previews/ebd560c7-3b68-4616-adfc-27d68ceb1c4c

     Type                          Name                  Plan
     pulumi:pulumi:Stack           test-aws-1655-pf-dev
 ~   ├─ aws:appconfig:Environment  res                   update
     ├─ aws:appconfig:Application  app
     └─ pulumi:providers:aws       aws-provider

Resources:
    ~ 1 to update
    3 unchanged

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be.
 details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::test-aws-1655-pf::pulumi:pulumi:Stack::test-aws-1655-pf-dev]
    ~ aws:appconfig/environment:Environment: (update)
        [id=e2suou4:3u5gdcd]
        [urn=urn:pulumi:dev::test-aws-1655-pf::aws:appconfig/environment:Environment::res]
        [provider=urn:pulumi:dev::test-aws-1655-pf::pulumi:providers:aws::aws-provider::4846d995-be31-41cf-8a47-f33b54bdde22]
        applicationId: "3u5gdcd"
        name         : "pf-tags-test"

Do you want to perform this refresh?
No resources will be modified as part of this refresh; just your stack's state will be.

```

### Affected Resource(s)

_No response_

### Output of `pulumi about`

```
CLI          
Version      3.120.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME  VERSION
resource  aws   unknown
language  yaml  unknown

Host     
OS       darwin
Version  14.5
Arch     arm64

This project is written in yaml

Current Stack: chall-pulumi-corp/test-aws-1655-pf/dev

TYPE                                   URN
pulumi:pulumi:Stack                    urn:pulumi:dev::test-aws-1655-pf::pulumi:pulumi:Stack::test-aws-1655-pf-dev
pulumi:providers:aws                   urn:pulumi:dev::test-aws-1655-pf::pulumi:providers:aws::aws-provider
pulumi:providers:aws                   urn:pulumi:dev::test-aws-1655-pf::pulumi:providers:aws::default
aws:appconfig/application:Application  urn:pulumi:dev::test-aws-1655-pf::aws:appconfig/application:Application::app
aws:appconfig/environment:Environment  urn:pulumi:dev::test-aws-1655-pf::aws:appconfig/environment:Environment::res


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/chall-pulumi-corp
User           chall-pulumi-corp
Organizations  chall-pulumi-corp, pulumi
Token type     personal

No dependencies found

Pulumi locates its logs in /var/folders/3b/6mr1jkqx7r797ff75k27jfjc0000gn/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by corymhall**
We have special logic around applying default provider tags to
resources. This logic only applied to the `Check` call which means it
was not applied when you were importing resources. This PR extends that
logic to also run during the `Read` call by utilizing `TransformOutputs`.

While it is true that `TransformOutputs` also runs during `Create` & `Update`
this is a side effect that I think is ok. From my understanding `tags` and `tagsAll`
should always be equal. If we have an additional place where we make sure they are equal
it shouldn't harm anything.

I've added tests (see `testTagsPulumiLifecycle`) which test the complete lifecycle of a pulumi program

1. `Up` with both provider `defaultTags`/`ignoreTags` and resource level `tags`
    1a. Run validations on result
2. `Refresh` with no changes
3. `Import` using the resource option. Ensures resource can be successfully imported
   3a. Allows for a hook to be run prior to import being run. e.g. Add tags remotely
4. `Import` using the CLI. Ensures resources can be successfully imported
   4a. Allows for a hook to be run prior to import being run. e.g. Add tags remotely
5. `Refresh` with no changes

fix #4030, fix #4080, fix #3311

### CODE REVIEW

File: provider/tags.go [hunk 1]
```diff
@@ -57,6 +57,40 @@ func applyTags(
 	}
 	if allTags.IsNull() {
 		delete(ret, "tags")
+		delete(ret, "tagsAll")
```
Comment (corymhall) [inline provider/tags.go:60]: This fixes #4080

Comment (t0yv0) [reply provider/tags.go:60]: So null tagsAll is replaced with simply missing. That's reasonable I think.

File: provider/tags.go [hunk 2]
```diff
@@ -57,6 +57,40 @@ func applyTags(
...
+	}
+
+	meta := resource.PropertyMap{}
+	if at, ok := config["tagsAll"]; ok {
+		meta["defaultTags"] = resource.NewObjectProperty(resource.PropertyMap{
+			"tags": at,
+		})
+	}
+
+	allTags, err := mergeTags(ctx, configTags, meta)
```
Comment (t0yv0) [inline provider/tags.go:87]: I'd appreciate a little bit of elaboration here on what we're trying to do, and how does it work, I see this:

As written, `allTags = mergeTags(ctx, config.tags, {defaultTags: config.tagsAll})`. 

I *think* if I recall what TransformOutputs is doing this will be assigning config to the tags and tagsAll coming out of the TF provider. This seems to then ignore the current defaultTags on the provider itself as it were. 

Why does this work? I thought perhaps we're not trusting the tags_all output from the provider internals, is it useful here?

File: provider/tags.go [hunk 3]
```diff
@@ -57,6 +57,40 @@ func applyTags(
 	}
 	if allTags.IsNull() {
 		delete(ret, "tags")
+		delete(ret, "tagsAll")
+		return ret, nil
+	}
+	ret["tags"] = allTags
```
Comment (flostadler) [inline provider/tags.go:63]: Why do we set `allTags` to `tags`? Shouldn't `tags` only include the tags specified on the resource?

Comment (t0yv0) [reply provider/tags.go:63]: Yeah I was also confused here, I was expecting something like this:

- (1) we receive data from the Read call that has "tags" and "tags_all"

- (2) I think here we need to understand what this data is and do we trust it; e.g. the TF provider would be grabbing all tags from the AWS hopefully, but then it would also possibly applying the defaultTags to that result to either union or exclude them? We had to disable this behavior for Create/Update lifecycle since we couldn't get the implementation to behave correctly and trust it; perhaps something similar needs to be tweaked here for reads 

- (3) suppose we figured out (2) correctly and we obtained what we believe is the set of in-AWS resource tags. Now what do we decide to surface as "tags". Perhaps here we want to exclude surfacing a k:v pair in "tags" if the defaultTags already has it set at provider level. So perhaps take the set difference here?

Unfortunately it's more complicated than this as TransformOutputs hook is hiding some differences around the context this code is executing in. Let me add below.

**Comment by t0yv0** [comment]
ResourceProvider.Read we're trying to modify here is very overloaded in Pulumi unfortunately, so  there's a matrix of case here to consider. 

#### Case 1: pulumi import on the CLI

```
pulumi import 'aws:iam/user:User' name id
```

Relatively simple version where there are no program inputs to consider and the objective is to generate a minimal program. The program would be minimal if all cloud tags that are already in defaultTags are omitted.  

#### Case 2:  import with resource option

I think this is somehow meaningfully different from vanilla import because it has some resource inputs to consider from the program.  If the program specifies an input tag k:v in the inputs and the cloud doesn't have it or has a contradicting value, Pulumi should probably be failing saying that the inputs do not match so that the user fixes up the program before proceeding. If the program does *not* specify the tag k:v that cloud has, but defaultTags do, then we should proceed without warning.

```
opts=pulumi.ResourceOptions(import_=bucket_name)
```

### Case 3: pulumi refresh

This one is interesting because it starts engaging bridge heuristics ExtractInputsFromOutputs to try to guess which cloud value is an input and which one is an output. I think it's pretty crude right now and might not do what we'd like for tags, worth thinking through.

### Case 4: Bucket.get()

This one I have a bit of a knowledge gap and need to brush up on, but I think it will also call Read.

**Comment by t0yv0** [comment]
The additional matrix dimension is that resources can be PF based or SDKv2 based and the underlying TF behavior can be different .

**Comment by t0yv0** [comment]
TransformOutputs is a blunt tool since it will not only modify Read results, but also modify Create and Update results, and it can't yet understand which kind of Read context it's operating in. There's some additional burden on verifying these changes don't affect Create/Update but looks like the test suite passed so that might be working just fine. I'm wondering if we need something more granular here..

**Comment by corymhall** [comment]
@t0yv0 @flostadler here is what my current understanding is.

There are two fields that track tags on a resource;

- `tags` - These are the tags that are applied to the resource itself.
```ts
new aws.s3.BucketV2('bucket', {
  tags: {
    SomeKey: 'SomeValue',
  },
});
```
- `tagsAll`/`defaultTags` - These are the tags that are specified on the provider and apply to all resources under that provider.
```ts
new aws.Provider('aws', {
  defaultTags: {
    tags: {
      GlobalTag: 'Value',
    },
  },
});
```

When it comes time to apply these tags to a resource we merge the tags into a single list of tags. The way that we do this is a hack on the pulumi side as part of the `PreCheckCallback`.  All the tags specified in `defaultTags` are merged into the resource `tags` so that it contains all the tags that need to be created on the resource. This runs during the `Check` request which runs prior to `Create` & `Update` so that the output of `Check` contains the merged `tags` and is passed into `Create`/`Update`. 

**From what I can tell, the intention is for `tags` and `tagsAll` to always be equal.**

## Example

If I were to create a resource with this configuration (both `defaultTags` & `tags`) 
```ts
const provider = new aws.Provider('aws', {
  defaultTags: {
    tags: {
      GlobalTag: 'Value',
    },
  },
});

new aws.s3.BucketV2('bucket', {
  tags: {
    LocalTag: 'Value',
  },
}, { provider });
```

The state of the bucket resource will have the tags like this (merged together):

```json
{
  "resources": [
    {
        "type": "aws:s3/bucketV2:BucketV2",
        "inputs": {
            "tags": {
                "GlobalTag": "Value",
                "LocalTag": "Value"
            },
            "tagsAll": {
                "GlobalTag": "Value",
                "LocalTag": "Value"
            }
        },
        "outputs": {
            "tags": {
                "GlobalTag": "Value",
                "LocalTag": "Value"
            },
            "tagsAll": {
                "GlobalTag": "Value",
                "LocalTag": "Value"
            }
        }
    }
  ]
}
```

If I were to then go an add a new tag in the console `ConsoleTag` and change the values of `GlobalTag` & `LocalTag` and then run a refresh it will show a diff for both `tags` and `tags` all. Everything works correctly because the inputs to read & diff is the current state which contains _all_ the tags.

```json
{
  "method": "/pulumirpc.ResourceProvider/Read",
  "request": {...},
  "response": {
      "tags": {
          "GlobalTag": "ValueOther",
          "LocalTag": "ValueOther",
          "ConsoleTag": "Value"
      },
      "tagsAll": {
          "GlobalTag": "ValueOther",
          "LocalTag": "ValueOther",
          "ConsoleTag": "Value"
      },
    "inputs": {
      "tags": {
          "GlobalTag": "Value",
          "LocalTag": "Value"
      },
      "tagsAll": {
          "GlobalTag": "Value",
          "LocalTag": "Value"
      }
    }
  }
}
{
  "method": "/pulumirpc.ResourceProvider/Diff",
  "request": {
    "olds": {
      "tags": {
          "GlobalTag": "ValueOther",
          "LocalTag": "ValueOther",
          "ConsoleTag": "Value"
      },
      "tagsAll": {
          "GlobalTag": "ValueOther",
          "LocalTag": "ValueOther",
          "ConsoleTag": "Value"
      }
    },
    "news": {
      "tags": {
          "GlobalTag": "Value",
          "LocalTag": "Value"
      },
      "tagsAll": {
          "GlobalTag": "Value",
          "LocalTag": "Value"
      }
    },
    "oldInputs": {
      "tags": {
          "GlobalTag": "Value",
          "LocalTag": "Value"
      },
      "tagsAll": {
          "GlobalTag": "Value",
          "LocalTag": "Value"
      }
    }
  },
  "response": {
    "changes": "DIFF_SOME",
    "diffs": ["tags","tags","tags","tagsAll","tagsAll","tagsAll"],
    "detailedDiff": {...},
    "hasDetailedDiff": true
  }
}
```

If instead I try and import a resource with the same configuration of tags there would be no existing `state` to rely on. The state would be produced by the output of the `read` call. When I run an import it will call `Read -> Check -> Diff`. The inputs to `Diff` will be:

- `olds`:  produced by `Read`. There is a difference between `tags` & `tagsAll` because it is not merging them together.
- `news`: produced by `Check`. Check  runs `PreCheckCallBack` and produces a merged `tags` & `tagsAll`.

This always leads to a diff because we are comparing an unmerged `tags` & `tagsAll` produced by `Read` with a merged `tags` & `tagsAll` produced by `Check`.

```json
{
  "method": "/pulumirpc.ResourceProvider/Read",
  "request": {"properties": {}},
  "response": {
    "properties": {
      "tags": {
        "LocalTag": "Value"
      },
      "tagsAll": {
        "GlobalTag": "Value"
      },
    },
    "inputs": {
      "tags": {
        "LocalTag": "Value"
      },
      "tagsAll": {
        "GlobalTag": "Value"
      }
    }
  }
}
{
  "method": "/pulumirpc.ResourceProvider/Check",
  "request": {
    "olds": {
      "tags": {
       "LocalTag": "Value"
      },
      "tagsAll": {
        "GlobalTag": "Value"
      }
    },
    "news": {
      "tags": {
         "LocalTag": "Value" 
      }
    }
  },
  "response": {
    "inputs": {
      "tags": {
         "LocalTag": "Value" ,
        "GlobalTag": "Value"
      },
      "tagsAll": {
         "LocalTag": "Value" ,
        "GlobalTag": "Value"
      }
    }
  }
}
{
  "method": "/pulumirpc.ResourceProvider/Diff",
  "request": {
    "olds": {
      "tags": {
         "LocalTag": "Value" 
      },
      "tagsAll": {
        "GlobalTag": "Value"
      }
    },
    "news": {
      "tags": {
         "LocalTag": "Value" ,
        "GlobalTag": "Value"
      },
      "tagsAll": {
         "LocalTag": "Value" ,
        "GlobalTag": "Value"
      }
    },
    "oldInputs": {
      "tags": {
         "LocalTag": "Value" 
      },
      "tagsAll": {
         "LocalTag": "Value" ,
        "GlobalTag": "Value"
      }
    }
  },
  "response": {
    "changes": "DIFF_SOME",
    "diffs": [ "tags", "tags", "tags" ],
    "detailedDiff": {...},
    "hasDetailedDiff": true
  }
}
```

What this PR attempts to do is to apply the same type of hack that we do in `PreCheckCallback` to the `TransformOutputs` that is run during `Read`, `Create`, & `Update`. Looking at the above example, we need the `Read` call to produce a merged `tags` & `tagsAll`, which we can do as part of `TransformOutputs`. 


> TransformOutputs is a blunt tool since it will not only modify Read results, but also modify Create and Update results, and it can't yet understand which kind of Read context it's operating in. 

I think this only matters in a case where we _want_ `tags` & `tagsAll` (on a resource) to be different. Unless I am misunderstanding something I don't think there is ever a scenario where this is true. In that case it shouldn't matter that we merge `tags` & `tagsAll` in an additional callback.

**Comment by VenelinMartinov** [comment]
@corymhall Do you have some background on 

> From what I can tell, the intention is for tags and tagsAll to always be equal.

This is not what TF does:

```hcl
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      GlobalTag = "GlobalVal"
    }
  }
}

# s3 bucket
resource "aws_s3_bucket" "bucket" {
  bucket_prefix = "mybucket"
  tags = {
    "localTag" = "localValue"
  }
}
```

produces 

```
"tags": {
  "localTag": "localValue"
},
"tags_all": {
  "GlobalTag": "GlobalVal",
  "localTag": "localValue"
},
```

which makes sense to me. Why are we doing something different here?

**Comment by corymhall** [comment]
> which makes sense to me. Why are we doing something different here?

Apparently there are a lot of upstream issues around tagging and we decided to do something about it on our side. I think @t0yv0 and @iwahbe are most familiar with this and they are both out this week.

https://github.com/pulumi/pulumi-aws/blob/00639674e4d93c39c47bb6ab3a67f96a58522ea4/provider/tags.go#L25-L45

**Comment by flostadler** [comment]
What if we just create a test for each of the scenarios Anton mentioned? I think that should ensure nothing unexpected breaks.
The cli import might be tricky to test, but we can also test that manually if necessary.

**Comment by VenelinMartinov** [comment]
Thanks for the background @corymhall 

> The cli import might be tricky to test, but we can also test that manually if necessary.

https://github.com/pulumi/pulumi-aws/pull/3859 has an example of importing in a test.

File: provider/resources.go [hunk 4]
```diff
@@ -5945,6 +5945,19 @@ compatibility shim in favor of the new "name" field.`)
...
+		if transform := prov.Resources[key].TransformOutputs; transform != nil {
+			prov.Resources[key].TransformOutputs = func(ctx context.Context, pm resource.PropertyMap) (resource.PropertyMap, error) {
+				config, err := transform(ctx, pm)
+				if err != nil {
+					return nil, err
+				}
+				return applyTagsOutputs(ctx, config)
+			}
+		} else {
+			prov.Resources[key].TransformOutputs = applyTagsOutputs
```
[the remark this answers is not in the document]
Comment (corymhall) [reply provider/resources.go:5958]: It's a side effect, but as long as it is true that `tags` and `defaultTags` should always be equal then I think we are fine.

File: patches/0038-Restore-legacy-bucket.patch [hunk 5]
```diff
@@ -5,10 +5,10 @@ Subject: [PATCH] Restore legacy bucket
 
 
 diff --git a/go.mod b/go.mod
-index 6d14fe0fc8..af57d1b01c 100644
+index f2ebf59e9a..aabe9bd190 100644
```
Comment (flostadler) [inline patches/0038-Restore-legacy-bucket.patch:8]: Why's that happening?

File: provider/provider_yaml_test.go [hunk 6]
```diff
@@ -459,7 +468,431 @@ func TestS3BucketObjectDeprecation(t *testing.T) {
...
+			assert.Equal(t, expectedTags, stackOutputTags.Value)
+		}
+	}
+
+	steps := []tagsTestStep{
+		// Pulumi maintains it's own version of aws:s3:Bucket in
+		// `s3legacy/bucket_legacy.go`. Because we don't have any
+		// terraform-provider-aws maintainers to ensure our tagging works the same
+		// way as other resource's tagging, we give our own bucket special testing
+		// to make sure that tags work.
```
Comment (flostadler) [inline provider/provider_yaml_test.go:537]: Nice! That's awesome

File: provider/provider_yaml_test.go [hunk 7]
```diff
@@ -459,7 +468,431 @@ func TestS3BucketObjectDeprecation(t *testing.T) {
...
+		{
+			name: "pf_ignore_tags", token: "aws:appconfig:Environment", typ: "aws:appconfig/environment:Environment",
+			tags: map[string]interface{}{
+				"LocalTag": "foo",
+			},
+			ignoreTagKeys: []string{"IgnoreKey"},
+			preImportHook: func(t *testing.T, outputs auto.OutputMap) {
+				t.Helper()
+				resArn := outputs["resArn"].Value.(string)
+				addAppconfigEnvironmentTags(context.Background(), resArn, map[string]string{
```
Comment (flostadler) [inline provider/provider_yaml_test.go:683]: Nit: we could generalize this using `tag:TagResources` which can tag all taggable resources.

File: provider/tags_test.go [hunk 8]
```diff
@@ -220,6 +220,187 @@ func TestApplyTags(t *testing.T) {
...
+				}),
+			},
+			expect: resource.PropertyMap{
+				"tags": resource.NewObjectProperty(resource.PropertyMap{
+					"tag1": resource.NewStringProperty("tag1v"),
+				}),
+			},
+		},
+		{
+			name: "provier sets a tag",
```
Comment (flostadler) [inline provider/tags_test.go:335]:
```suggestion
			name: "provider sets a tag",
```

File: provider/provider_yaml_test.go [hunk 9]
```diff
@@ -459,7 +468,431 @@ func TestS3BucketObjectDeprecation(t *testing.T) {
...
+	_, err = stack.Preview(ctx, optpreview.Refresh(), optpreview.ExpectNoChanges())
+	assert.NoError(t, err)
+}
+
+// generateTagsTest generates a pulumi program for the given test step
+// and writes it to the test directory
+func generateTagsTest(t *testing.T, step tagsTestStep, testPath string, importId string) {
+	template := `name: test-aws-%s
+runtime: yaml
+resources:
```
Comment (flostadler) [inline provider/provider_yaml_test.go:799]: We should test the static `get` functions as well ideally because we're changing the behavior of read

**Review by flostadler — COMMENTED** [review]
Is my understanding correct that instead of following terraform's behavior of merging `tags` and `default_tags` into `tags_all`, we manually do the merge and set the result to both tags/tagsAll. Your change is adding that to the read code path as well.

What I'm still missing is why we need all of the special tag handling? In what areas does terraforms tagging fall short? Are we sure that it's still broken (the tests you've added might be good regression tests to check if we still need it)? Those are rather questions for @t0yv0 / @iwahbe I guess.

The change looks good to me, the tests are great! I think we should add some tests for the static get functions as well though.

File: patches/0038-Restore-legacy-bucket.patch (hunk 5 above)
Comment (corymhall) [reply patches/0038-Restore-legacy-bucket.patch]: fixed.

File: provider/provider_yaml_test.go (hunk 7 above)
Comment (corymhall) [reply provider/provider_yaml_test.go]: Updated!

File: provider/provider_yaml_test.go [hunk 10]
```diff
@@ -452,14 +470,439 @@ func TestIMDSAuth(t *testing.T) {
...
+	isNil := func(val interface{}) bool {
+		if val == nil {
+			return true
+		}
+		v, ok := val.(map[string]interface{})
+		return ok && len(v) == 0
+	}
+	validateOutputTags := func(outputs auto.OutputMap, expectedTags map[string]interface{}) {
+		stackOutputTags := outputs["actual"]
+		if !isNil(expectedTags) || !isNil(stackOutputTags) {
```
Comment (t0yv0) [inline provider/provider_yaml_test.go:537]: This skips checking if one map is nil and the other isn't, perhaps also assert that to make this more complete?

File: provider/provider_yaml_test.go [hunk 11]
```diff
@@ -452,14 +470,439 @@ func TestIMDSAuth(t *testing.T) {
...
+	options := map[string]interface{}{
+		"provider": "${aws-provider}",
+	}
+
+	if importId != "" {
+		options["import"] = importId
+	}
+
+	var expandMap func(level int, v interface{}) string
+	expandMap = func(level int, v interface{}) string {
```
Comment (t0yv0) [inline provider/provider_yaml_test.go:830]: Oof too bad there is no existing helper for this. Theoretically YAML is a text representation of json-like trees and could operate at that level perhaps followed by yaml.Marshal.

File: provider/provider_test.go [hunk 12]
```diff
@@ -34,6 +36,24 @@ func getEnvRegion(t *testing.T) string {
...
+	workspace := ptest.CurrentStack().Workspace()
+	for k, v := range workspace.GetEnvVars() {
+		env = append(env, fmt.Sprintf("%s=%s", k, v))
+	}
+	stdin := bytes.NewReader([]byte{})
+	var arguments []string
+	arguments = append(arguments, args...)
+	arguments = append(arguments, "-s", ptest.CurrentStack().Name())
+	s1, s2, code, err := workspace.PulumiCommand().Run(ctx, workdir, stdin, nil, nil, env, arguments...)
+	t.Logf("import stdout: %s", s1)
```
Comment (t0yv0) [inline provider/provider_test.go:51]: not necessarily import at this point, right? some arbitrary pulumi command stdout

File: provider/provider_yaml_test.go [hunk 13]
```diff
@@ -452,14 +470,439 @@ func TestIMDSAuth(t *testing.T) {
...
+	}
+
+	t.Log("refresh...")
+	_, err = stack.Refresh(ctx, optrefresh.ExpectNoChanges())
+	assert.NoError(t, err)
+
+	t.Log("delete state...")
+	execPulumi(t, ptest, stepDir, "state", "delete", urn)
+
+	// import using the import resource option
```
Comment (t0yv0) [inline provider/provider_yaml_test.go:767]: Excellent.

**Comment by t0yv0** [comment]
I gave this a quick read this is looking pretty good. 

- Lifecycle testing imports this can add significant peace of mind around the system behavior, excellent 👏  
  - The correct behavior is probably evident in the logs but asserts could be tightened a bit to make it more precise, namely not only verifying import succeeds but it produces the "desired" program - that is one that when run with `pulumi up` results in a state with the correct tag set
 
-  `tags and tagsAll to always be equal` that's exactly right; in current Pulumi interpretation tags output is the union of defaultTags and 'proper' tags; and tagsAll is the same thing that's marked deprecated but retained for compat

- it is a bit weird that the fix merges tagsAll and tags, instead of merging defaultTags and tags, but it probably accomplishes the same thing because TF might be merging defaultTags and tags to compute tagsAll internally in Read; I did not know we could rely on this since some of our patches disable `func (r *ResourceWithConfigure) SetTagsAll` and try to remove some of this functionality, but sounds like it is still present? I suspect a more robust fix can be obtained by ignoring tagsAll returned in the outputs and just merging tags and defaultTags? 

- the question on why not just remove all tags-related patches is a good one, I see it's tracked in https://github.com/pulumi/pulumi-aws/issues/4230 - this would be desirable but during last audit there still were open upstream issues; once we have a more comprehensive test suite that passes that'd be preferable to doing the work in the wrapped provider

**Comment by corymhall** [comment]
@t0yv0 

> The correct behavior is probably evident in the logs but asserts could be tightened a bit to make it more precise, namely not only verifying import succeeds but it produces the "desired" program

That's a good idea, i'll work on adding that.

> once we have a more comprehensive test suite that passes that'd be preferable to doing the work in the wrapped provider

This is one of my big questions - what kind of tests do we need to add in order to be confident of the changes?

>  I suspect a more robust fix can be obtained by ignoring tagsAll returned in the outputs and just merging tags and defaultTags?

This might be more inline with the current `PreCheckCallback` hook, but we currently do not get the `defaultTags` from config in the `TransformOutputs`. Should we create a new `PostReadCallback` hook in the bridge to cover this scenario?

**Comment by corymhall** [comment]
@t0yv0 

> The correct behavior is probably evident in the logs but asserts could be tightened a bit to make it more precise, namely not only verifying import succeeds but it produces the "desired" program

I'm actually not sure that it is possible to generate the desire program. I think we can choose to have `pulumi up` (with import) work _or_ have `pulumi import` generate a correct program, but not both.

In the current state (before this PR):

`pulumi import` generates the program based on `Read`  (where `tags != tagsAll`)
```json
{
  "method": "/pulumirpc.ResourceProvider/Read",
  "request": {},
  "response": {
    "inputs": {
      "tags": {
        "LocalTag": "foo"
      },
      "tagsAll": {
        "GlobalTag": "bar",
        "LocalTag": "foo"
      }
    }
  }
}
```

`pulumi up` performs the diff based on the response from `Read` vs the response from `Check` (which is setting `tags=tagsAll`)

```json
{
  "method": "/pulumirpc.ResourceProvider/Check",
  "request": {...},
  "response": {
    "inputs": {
      "tags": {
        "GlobalTag": "bar",
        "LocalTag": "foo"
      },
      "tagsAll": {
        "GlobalTag": "bar",
        "LocalTag": "foo"
      }
    }
  }
}
```

So we have two options:

1. Have `tags != tagsAll` in order for `pulumi import` to generate the correct program
2. Have `tags == tagsAll` in order for  `pulumi up` to import successfully

**Comment by iwahbe** [comment]
We need the special tags handling because terraform-provider-aws's native tags handling relies on refresh for correctness, and so doesn't work for most Pulumi users.

**Comment by corymhall** [comment]
> We need the special tags handling because terraform-provider-aws's native tags handling relies on refresh for correctness, and so doesn't work for most Pulumi users.

@iwahbe can you expand on what this means?

**Comment by iwahbe** [comment]
> > We need the special tags handling because terraform-provider-aws's native tags handling relies on refresh for correctness, and so doesn't work for most Pulumi users.
> 
> @iwahbe can you expand on what this means?

I expanded a bit here: https://github.com/pulumi/pulumi-aws/issues/4230#issuecomment-2237416043.

Basically, if you run `terraform apply -refresh=false` then default tags do not work as expected (they don't delete, or they don't add...). This has improved since we last looked at it, but a cursory test shows that major functionality still doesn't work as expected.

File: provider/provider_yaml_test.go (hunk 9 above)
Comment (corymhall) [reply provider/provider_yaml_test.go:809]: Added!

File: provider/provider_yaml_test.go [hunk 14]
```diff
@@ -452,14 +470,439 @@ func TestIMDSAuth(t *testing.T) {
...
+				"GlobalTag": "bar",
+			},
+			postUpHook: func(t *testing.T, outputs auto.OutputMap) {
+				validateOutputTags(outputs, map[string]interface{}{
+					"LocalTag":  "foo",
+					"GlobalTag": "bar",
+				})
+				bucketName := outputs["id"].Value.(string)
+				tags := getBucketTagging(context.Background(), bucketName)
+				assert.Subset(t, tags, []types.Tag{
```
Comment (t0yv0) [inline provider/provider_yaml_test.go:563]: Subset and not Equal? Why? Interesting.

File: examples/examples_go_test.go [hunk 15]
```diff
@@ -251,12 +251,16 @@ func (st tagsState) validateStateResult(phase int) func(
...
 			if k == "bucket" {
+				// getTags := stack.Outputs["get-bucket"].(string)
+				// assert.Equal(t, v.(string), getTags)
 				bucketName := stack.Outputs["bucket-name"].(string)
 				st.assertTagsEqualWithRetry(t,
 					fetchBucketTags(bucketName),
 					"bad bucket tags")
 			}
 			if k == "legacy-bucket" {
+				// getTags := stack.Outputs["get-legacy-bucket"].(string)
```
Comment (t0yv0) [inline examples/examples_go_test.go:262]: Are these comments still useful?

File: examples/tags-combinations-go/main.go [hunk 16]
```diff
@@ -71,12 +71,40 @@ func main() {
...
+		if err != nil {
+			return err
+		}
+
+		getEnv, err := appconfig.GetEnvironment(ctx, "get-testappconfigenv"+testIdent, env.ID(), &appconfig.EnvironmentState{}, pulumi.Provider(p))
+		if err != nil {
+			return err
+		}
+
+		// refresh doesn't work for `forceDelete` & `acl` uncomment when fixed
```
Comment (t0yv0) [inline examples/tags-combinations-go/main.go:87]: This is interesting, is this something worth linking a ticket to? Thank you.

File: examples/examples_go_test.go (hunk 15 above)
Comment (corymhall) [reply examples/examples_go_test.go:264]: Added another comment with link to the issue. When the issue is fixed the code can be uncommented.

File: examples/tags-combinations-go/main.go (hunk 16 above)
Comment (corymhall) [reply examples/tags-combinations-go/main.go]: Added another comment with link to the issue.

File: provider/provider_yaml_test.go (hunk 14 above)
Comment (corymhall) [reply provider/provider_yaml_test.go]: Updated.
