### PR TITLE
Fix updating tags on aws_launch_template

### LINKED ISSUE #1504: aws:ec2:LaunchTemplate update_default_version Fails on AWS Provider
I upgraded the AWS provider from 3.23 to the latest 4.5.1 recently to do a Pulumi 3.x upgrade. Noticed some code that sets `update_default_version` on this provider fails now when doing a pulumi update on the existing resources.

## Expected behavior
No changes should have been seen by the provider and updateDefaultVersion should continue to function as desired.

## Current behavior
```
  aws:ec2:LaunchTemplate (ci-general):
    error: 1 error occurred:
    	* updating urn:pulumi:ci::aws-eks-py::aws:ec2/launchTemplate:LaunchTemplate::ci-general: 1 error occurred:
    	* error modifying Launch Template (lt-<REDACTED>): InvalidParameterValue: Invalid launch template version: either '$Default', '$Latest', or a numeric version are allowed.
```

also, it doesn't even show up in the list of diffSet, so something tells me the provider is misbehaving internally here.

```
     pulumi:pulumi:Stack        aws-eks-py-ci   **failed**              1 error
 ~   ├─ aws:ec2:LaunchTemplate  ci-kiam-server  **updating failed**     [diff: -tagsAll~tags]; 1 error
 ~   └─ aws:ec2:LaunchTemplate  ci-general      **updating failed**     [diff: -tagsAll~tags]; 1 error
```

## Steps to reproduce
We are using the Python dialect. Create a `pulumi_aws.ec2.LaunchTemplate` resource and set the `update_default_version` attribute to True.

## Context (Environment)
Existing resource was present and may or may not affect the outcome of the result. This was a LaunchTemplate whose versioning updating was working just fine prior to upgrading the pulumi-aws provider to 4.5.1 and pulumi to 3.2.1.

This seems like a really old Terraform issue to be honest, that somehow resurfaced itself (regression?) in the newer AWS provider. https://github.com/hashicorp/terraform-provider-aws/issues/4655

## Affected feature
N/A

### PR DESCRIPTION
**Pull request by t0yv0**
Fixes #1504

Due to discrepancies between TF and Pulumi Bridged provider life cycle, editing tags on a Launch Template resource caused failure in pulumi-aws. This is now fixed by opting in this resource to the PlanResourceChange behavior that tracks TF lifecycle more closely.

### CODE REVIEW

File: provider/provider_python_test.go [hunk 1]
```diff
@@ -30,6 +32,36 @@ func TestRegress3196(t *testing.T) {
...
 }
 
+func TestRegress1504(t *testing.T) {
+	if testing.Short() {
+		t.Skipf("Skipping test in -short mode because it needs cloud credentials")
+		return
+	}
+	test := getPythonBaseOptions(t).
+		With(integration.ProgramTestOptions{
+			// Not ideal, need investigation:
```
Comment (t0yv0) [inline provider/provider_python_test.go:42]: Filed https://github.com/pulumi/pulumi-aws/issues/3686

**Review by mjeffryes — APPROVED** [review]
I can't claim to understand the details of what adding PlanResourceChange to the resource does, but I find the test convincing.
