### PR TITLE
Suppress undefined to default diffs on aws.autoscaling.Group

### LINKED ISSUE #4457: [import] AWS autoscaling group import and subsequent `up` tries to fix defaults to actual default values
### What happened?

I imported an autoscaling group with pulumi import, added the generated code to the pulumi program, and issued `pulumi preview`.

Expected: no changes.

Actual: pulumi insists on fixing some properties that are set to "Default" in the cloud reality to their respective actual default values. This is undesirable.

```
      + forceDelete                  : false
      + forceDeleteWarmPool          : false
      + ignoreFailedScalingActivities: false
      + waitForCapacityTimeout       : "10m"
```

I inspected the state using `pulumi stack export`, and all these properties are `null` in the state after import, and they are not specified in code either. If the state says `null` and the cloud reality says "Default" (as an option selected in a select widget in the AWS Console), and the program says nothing, then where does `false` or `"10m"` even come from?

### Example

Import command:
```
pulumi import --generate-code 'aws:autoscaling/group:Group' platform Infra-ECS-Cluster-zaffre-37cd4e5b-ECSAutoScalingGroup-982zexeihkOe
```

Generated code:
```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

const platform = new aws.autoscaling.Group("platform", {
    availabilityZones: ["eu-central-1a"],
    defaultCooldown: 300,
    healthCheckGracePeriod: 0,
    healthCheckType: "EC2",
    launchTemplate: {
        id: "lt-0789d9b35b0a9d959",
        version: "$Latest",
    },
    maxSize: 2,
    minSize: 0,
    name: "Infra-ECS-Cluster-zaffre-37cd4e5b-ECSAutoScalingGroup-982zexeihkOe",
    serviceLinkedRoleArn: "arn:aws:iam::164629628951:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling",
    tags: [
        {
            key: "AmazonECSManaged",
            propagateAtLaunch: true,
            value: "",
        },
        {
            key: "Name",
            propagateAtLaunch: true,
            value: "ECS Instance - zaffre",
        },
    ],
}, {
    protect: true,
});
```

### Output of `pulumi about`

```
CLI          
Version      3.131.0
Go Version   go1.23.0
Go Compiler  gc

Plugins
KIND      NAME    VERSION
resource  aws     6.51.0
resource  aws     6.51.0
resource  awsx    2.14.0
resource  awsx    2.14.0
resource  docker  4.5.5
resource  docker  4.5.5
resource  docker  3.6.1
resource  docker  3.6.1
language  nodejs  unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in nodejs: executable='/home/rulatir/projects/zaffre/internment/nave/store/installed/node-modern/bin/node' version='v22.2.0'

Current Stack: organization/zuu-iac/permanent

TYPE                                   URN
[REDACTED]

Found no pending operations associated with permanent

Backend        
Name           berbelek
URL            s3://zuu-iac/attempts/PPM
User           rulatir
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: could not find either /home/rulatir/projects/zaffre/cloud/attempts/PPM/yarn.lock or /home/rulatir/projects/zaffre/cloud/attempts/PPM/package-lock.json
```

Note about the last warning: I chose `pnpm` during `pulumi new`; it seems `pulumi about` can't handle that yet.

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fix a regression in the import experience on aws.autoscaling.Group. Specifically the conflict between undefined and default values that `pulumi import` used to detect is no longer a conflict by automatically injecting DiffSuppressFunc for the relevant properties.

Fixes #4457

### CODE REVIEW

File: provider/provider_python_test.go [hunk 1]
```diff
@@ -70,6 +74,38 @@ func TestRegress2534(t *testing.T) {
...
+	autoGroupUrn := upResult.Outputs["autoGroupUrn"].Value.(string)
+	autoGroupName := upResult.Outputs["autoGroupName"].Value.(string)
+	workspace := ptest.CurrentStack().Workspace()
+
+	t.Logf("Provisioned autoscaling group with arn=%s and urn=%s and name=%s", autoGroupArn, autoGroupUrn, autoGroupName)
+	workdir := workspace.WorkDir()
+	t.Logf("workdir = %s", workdir)
+	importResult := execPulumi(t, ptest, workdir, "import", "aws:autoscaling/group:Group", "newag", autoGroupName, "--yes")
+
+	t.Logf("Editing the program to add the code recommended by import")
```
Comment (t0yv0) [inline provider/provider_python_test.go:90]: AFAIK we have no precedent of testing this, throwing in some automation, can generalize later if this is important.

File: provider/pkg/autoscaling/autoscaling.go [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+				return true
+			default:
+				return false
+			}
+		}
+	case schema.TypeString:
+		defaultValue, ok := field.Default.(string)
+		contract.Assertf(ok, "Default is not a string")
+		field.DiffSuppressFunc = func(k, oldValue, newValue string, d *schema.ResourceData) bool {
+			// Here oldValue must be undefined.
```
Comment (t0yv0) [inline provider/pkg/autoscaling/autoscaling.go:72]: Noting the difficulty here, the underlying APIs are interesting.

File: provider/pkg/autoscaling/autoscaling.go [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
+	"github.com/pulumi/pulumi/sdk/v3/go/common/util/contract"
+)
+
+// Customize resources in the autoscaling module.
+func ReconfigureResources(p *schema.Provider) {
+	autoscalingGroupReconfigure(mustGetResource(p, "aws_autoscaling_group"))
+}
+
+func autoscalingGroupReconfigure(r *schema.Resource) {
```
Comment (t0yv0) [inline provider/pkg/autoscaling/autoscaling.go:27]: This approach does *not* generate the default values into the Pulumi program, which is nice, while solving the problem. I was thinking of incubating it here but then considering generalizing. Instead of specifying the fields we can run automatic schema-based detection for fields that need it.

File: provider/pkg/autoscaling/autoscaling.go (hunk 2 above)
Comment (VenelinMartinov) [reply provider/pkg/autoscaling/autoscaling.go:72]: However, I think your use case can also be served by a TransformOutputs/TransformFromState hook, which should be able to distinguish between the two as it acts on the pulumi level.

File: provider/provider_python_test.go [hunk 4]
```diff
@@ -70,6 +74,38 @@ func TestRegress2534(t *testing.T) {
...
+	updatedPyBytes := bytes.ReplaceAll(pyBytes, []byte("# EXTRA CODE HERE"), []byte(extraCode))
+	err = os.WriteFile(mainPy, updatedPyBytes, 0600)
+	require.NoError(t, err)
+
+	t.Logf("Previewing the edited program")
+	previewResult := ptest.Preview(optpreview.ExpectNoChanges())
+	t.Logf("%s", previewResult.StdOut)
+	t.Logf("%s", previewResult.StdErr)
+
+	t.Logf("Un-protecting imported resources to make cleanup easier")
```
Comment (VenelinMartinov) [inline provider/provider_python_test.go:105]: import has a `--protect=false` parameter which you can use instead.

File: provider/provider_python_test.go [hunk 5]
```diff
@@ -70,6 +74,38 @@ func TestRegress2534(t *testing.T) {
...
+	upResult := ptest.Up()
+	autoGroupArn := upResult.Outputs["autoGroupArn"].Value.(string)
+	autoGroupUrn := upResult.Outputs["autoGroupUrn"].Value.(string)
+	autoGroupName := upResult.Outputs["autoGroupName"].Value.(string)
+	workspace := ptest.CurrentStack().Workspace()
+
+	t.Logf("Provisioned autoscaling group with arn=%s and urn=%s and name=%s", autoGroupArn, autoGroupUrn, autoGroupName)
+	workdir := workspace.WorkDir()
+	t.Logf("workdir = %s", workdir)
+	importResult := execPulumi(t, ptest, workdir, "import", "aws:autoscaling/group:Group", "newag", autoGroupName, "--yes")
```
Comment (VenelinMartinov) [inline provider/provider_python_test.go:88]: Pulumitest has import, you can use that instead: https://github.com/pulumi/providertest/blob/0ebd111cfb44be7fe7f56762ffe5d9feb8c1571f/pulumitest/import.go#L3

**Review by VenelinMartinov — COMMENTED** [review]
Have we considered using a `TransformOutputs` hook instead? That could be used to act on the import output, so that the fixup has to happen only once after the state is imported/

File: provider/pkg/autoscaling/autoscaling.go (hunk 2 above)
Comment (t0yv0) [reply provider/pkg/autoscaling/autoscaling.go:72]: I don't think so. TransformFromState does not apply to import-y reads, and as to TransformOutputs I suspect if used to inject default values will also print them into the import program which this neatly avoids, I can check this out quick.

Comment (VenelinMartinov) [reply provider/pkg/autoscaling/autoscaling.go:72]: >I don't think so. TransformFromState does not apply to import-y reads

Unfortunate - the docs suggest it does but it seems to only apply to the passed in state, not the one read from the provider.

Comment (t0yv0) [reply provider/pkg/autoscaling/autoscaling.go:72]: Checking up on this, looks like it does not in fact end up in defaults values being injected. Could be cleaner. I'll try harder.

**Comment by t0yv0** [comment]
I was a little surprised but TransformOutputs hook works well. It is able to eliminate the default values from the printed imported program which is good, and it also fixes the issue. The ability to be certain about undefined vs null vs empty is much appreciated. I think it also bypasses the problem with hypothetical defaults change.

File: provider/resources.go [hunk 6]
```diff
@@ -1246,6 +1246,47 @@ compatibility shim in favor of the new "name" field.`)
...
+						"forceDelete":                    defaultValue("force_delete"),
+						"forceDeleteWarmPool":            defaultValue("force_delete_warm_pool"),
+						"ignoreFailedScailingActivities": defaultValue("ignore_failed_scaling_activities"),
+						"waitForCapacityTimeout":         defaultValue("wait_for_capacity_timeout"),
+					}
+					return func(ctx context.Context, pm resource.PropertyMap) (resource.PropertyMap, error) {
+						r := pm.Copy()
+						for k, v := range defaults {
+							if value, defined := pm[resource.PropertyKey(k)]; defined && !value.IsNull() {
+								fmt.Println("TransformOutputs does not change already defined", k, value.String())
```
Comment (t0yv0) [inline provider/resources.go:1281]: Debug output

**Comment by t0yv0** [comment]
I've tested refresh and import_ option manually, seem to work as well for this with these changes.

File: provider/resources.go [hunk 7]
```diff
@@ -1246,6 +1246,45 @@ compatibility shim in favor of the new "name" field.`)
...
+							defb, ok := def.(bool)
+							contract.Assertf(ok, "Expected property %q Default() to be a bool", prop)
+							return resource.NewBoolProperty(defb)
+						default:
+							contract.Failf("Types other than string and bool are not supported yet")
+							return resource.NewNullProperty()
+						}
+					}
+					defaults := map[string]resource.PropertyValue{
+						"forceDelete":                    defaultValue("force_delete"),
```
Comment (flostadler) [inline provider/resources.go:1272]: Can we detect the props that need the defaults to be fixed? This would help us generalize this and also make maintenance a bit easier (no need to play catchup with upstream).

**Review by flostadler — APPROVED** [review]
LGTM

File: provider/resources.go (hunk 7 above)
Comment (t0yv0) [reply provider/resources.go:1272]: I think this works so well we should maybe change the bridge default behavior here in https://github.com/pulumi/pulumi-terraform-bridge/issues/2436 so that's how it works by default without the custom code.
