### PR TITLE
Read all AWS env vars

### LINKED ISSUE #252: Cannot authenticate on AWS using switchrole
Hello,

I'm trying to bootstrap my first pulumi project but I'm encountering an issue with the supported authentication method on AWS. 

If I'm using a profile in which my credentials are defined ( with `aws_access_key_id` and `aws_secret_access_key` ), it works like a charm. But that's not how we work in my company, we have a source account and we're using switchrole to jump from that source account to all other accouts ( this is standard AWS procedure when you're dealing with multiple accounts ).

Here's the look of my profiles in `~/.aws/config` : 

```
[profile myprofile]
role_arn = arn:aws:iam::<AWS destination account id>:role/<the role I'm going to impersonate>
mfa_serial = arn:aws:iam::<source AWS account ID>:mfa/<IAM User name on the source account>
source_profile = <the profile name in which my keys are defined for my source account>
```

Now when I'm using one of those profile, it fails : 
```
$ AWS_PROFILE=myprofile pulumi update
Previewing update of stack 'prod'
Previewing changes:

     Type                    Name               Plan          Info
 *   global                  global             no change     1 error
 +   └─ pulumi:pulumi:Stack  first-pulumi-prod  create        
 
Diagnostics:
  global: global
    error: unable to discover AWS AccessKeyID and/or SecretAccessKey - see https://pulumi.io/install/aws.html for details on configuration
 
error: an error occurred while advancing the preview
```

When using the same command line with my source profile ( the one with the keys ), I have the expected result :
```
      Type                 Name               Plan       Info
 +   pulumi:pulumi:Stack  first-pulumi-prod  create
 +   └─ aws:s3:Bucket     my-bucket          create

info: 2 changes previewed:
    + 2 resources to create

Do you want to perform this update?
  yes
> no
  details
```

Is there any configuration I'm missing or is it not possible for the moment to use an AWS profile with switchrole ?

Thanks

### PR DESCRIPTION
**Pull request by lukehoban**
For both programmatic access, and for pre-configuration, we must read in all the appropriate env vars.  We were previously failing to read many of the env vars for setting up programmatic access, and failing to read any of the env vars for pre-configuration checks.

Fixes #252

### CODE REVIEW

File: resources.go [hunk 1]
```diff
@@ -251,6 +259,16 @@ func Provider() tfbridge.ProviderInfo {
 		Repository:  "https://github.com/pulumi/pulumi-aws",
 		Version:     version.Version,
 		Config: map[string]*tfbridge.SchemaInfo{
+			"access_key": {
+				Default: &tfbridge.DefaultInfo{
+					EnvVars: []string{"AWS_ACCESS_KEY_ID"},
+				},
+			},
+			"secret_key": {
+				Default: &tfbridge.DefaultInfo{
```
Comment (cleverguy25) [inline resources.go]: Should AWS_PROFILE be somewhere here?

Comment (stack72) [reply resources.go]: It is just below this comment :) Line 280

**Comment by stack72** [comment]
@lukehoban just pushed a quick fix to the branch for the range statement
