### PR TITLE
Deprecate `name` on `aws.rds.Instance`

### LINKED ISSUE #2682: RDS Instance replacement when upgrading to 6.0
### What happened?

Upgrading from 5.x to 6.0 causes a replacement in `aws.rds.Instance`.

```
     Type                 Name        Plan        Info
     pulumi:pulumi:Stack  aws-ts-dev              
 +-  └─ aws:rds:Instance  postgresdb  replace     [diff: ~name]

Resources:
    +-1 to replace
    2 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::aws-ts::pulumi:pulumi:Stack::aws-ts-dev]
    ++aws:rds/instance:Instance: (create-replacement)
        [id=postgresdbd65b294]
        [urn=urn:pulumi:dev::aws-ts::aws:rds/instance:Instance::postgresdb]
        [provider: urn:pulumi:dev::aws-ts::pulumi:providers:aws::default_5_41_0::5199a248-3c92-4b11-ae4e-dbf860fd2c76 => urn:pulumi:dev::aws-ts::pulumi:providers:aws::default_6_0_0::output<string>]
      ~ name: "airflow" => "airflow"
    +-aws:rds/instance:Instance: (replace)
        [id=postgresdbd65b294]
        [urn=urn:pulumi:dev::aws-ts::aws:rds/instance:Instance::postgresdb]
        [provider: urn:pulumi:dev::aws-ts::pulumi:providers:aws::default_5_41_0::5199a248-3c92-4b11-ae4e-dbf860fd2c76 => urn:pulumi:dev::aws-ts::pulumi:providers:aws::default_6_0_0::output<string>]
      ~ name: "airflow" => "airflow"
    --aws:rds/instance:Instance: (delete-replaced)
        [id=postgresdbd65b294]
        [urn=urn:pulumi:dev::aws-ts::aws:rds/instance:Instance::postgresdb]
        [provider=urn:pulumi:dev::aws-ts::pulumi:providers:aws::default_5_41_0::5199a248-3c92-4b11-ae4e-dbf860fd2c76]
```

### Expected Behavior

No change in preview.

### Steps to reproduce

1. Deploy this program with the latest `^5.0.0` of AWS provider:

```
import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";
import * as random from "@pulumi/random";

const dbName = "airflow"
const dbUser = "airflow"

const airflowPassword = new random.RandomPassword(`airflow-password`, {
    length: 16,
    special: false,
});

const db = new aws.rds.Instance("postgresdb", {
    engine: "postgres",

    instanceClass: "db.t4g.micro",
    allocatedStorage: 30,

    name: dbName,
    username: dbUser,
    password: airflowPassword.result,

    skipFinalSnapshot: true,
});
```

2. Upgrade to 6.0.
3. Run `pulumi preview`.

### Output of `pulumi about`

```
CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.0.0
nodejs  unknown
random  4.13.2

Host     
OS       darwin
Version  13.4.1
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v20.4.0'

Current Stack: mikhail-pulumi-corp/aws-ts/dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::aws-ts::pulumi:pulumi:Stack::aws-ts-dev
pulumi:providers:random                     urn:pulumi:dev::aws-ts::pulumi:providers:random::default_4_13_2
random:index/randomPassword:RandomPassword  urn:pulumi:dev::aws-ts::random:index/randomPassword:RandomPassword::airflow-password
pulumi:providers:aws                        urn:pulumi:dev::aws-ts::pulumi:providers:aws::default_5_41_0
aws:rds/instance:Instance                   urn:pulumi:dev::aws-ts::aws:rds/instance:Instance::postgresdb


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/mikhail-pulumi-corp
User           mikhail-pulumi-corp
Organizations  mikhail-pulumi-corp, pulumi

Dependencies:
NAME            VERSION
@pulumi/aws     6.0.0
@pulumi/pulumi  3.74.0
@pulumi/random  4.13.2
@types/node     16.18.38

Pulumi locates its logs in /var/folders/8g/ntvfz6q153q0mx7k8h7_y1j80000gn/T/ by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by iwahbe**
Fixes #2682

We should have deprecated `name` in `v5.x`. We could then remove it here. Because we didn't remove it here, we need to deprecate it now, so we can remove at `v7.0.0`. 

We want the following properties when we deprecate `name`:
- Doesn't require a patch upstream.
- `name` is deprecated in the schema.
- `name` warns when used, directing the user to use `dbName` instead.
- `name` is still valid as an input.
- `name` is still valid as an output.

This PR works by back-porting `name` into the upstream schema from the `Provider() tfbridge.ProviderInfo` function. Since the upstream provider is no longer aware of `name`, we set `dbName` to the value of `name` and delete `name`. If both were provided, we error, just like `v5.42.0` did.

As implemented, we get:
- [X] Doesn't require a patch upstream.
- [X] `name` is deprecated in the schema.
- [x] `name` warns when used, directing the user to use `dbName` instead.
- [X] `name` is still valid as an input.
- [X] `name` is still valid as an output.

To warn when we need to, we need to patch the bridge to allow passing a logger into `PreCheckCallback`. This change will be non-breaking.

### CODE REVIEW

File: provider/resources.go [hunk 1]
```diff
@@ -7095,7 +7127,19 @@ func Provider() *tfbridge.ProviderInfo {
...
-		prov.Resources[key].PreCheckCallback = applyTags
+		if callback := prov.Resources[key].PreCheckCallback; callback != nil {
+			prov.Resources[key].PreCheckCallback = func(
+				ctx context.Context, config resource.PropertyMap, meta resource.PropertyMap,
+			) (resource.PropertyMap, error) {
+				config, err := callback(ctx, config, meta)
+				if err != nil {
+					return nil, err
+				}
+				return applyTags(ctx, config, meta)
```
Comment (guineveresaenger) [inline provider/resources.go:7138]: I'm not sure I understand the logic here.

- if a resource that hits this code path has a non-nil callback, we want to apply tags _after_ applying the existing callback function to the config?
- if a resource  that hits this code path _doesn't_ have a callback, or it is nil, we behave as before

Since `rds.Instance` is currently the only resource with an explicit callback, could there ever be a new PreCheckCallback that _doesn't_ want this to happen?

**Comment by iwahbe** [comment]
We can get the warning we want easily after we merge https://github.com/pulumi/pulumi-terraform-bridge/pull/1333.

File: provider/resources.go [hunk 2]
```diff
@@ -2840,6 +2840,38 @@ func Provider() *tfbridge.ProviderInfo {
...
+				PreCheckCallback: func(
+					ctx context.Context, config resource.PropertyMap, meta resource.PropertyMap,
+				) (resource.PropertyMap, error) {
+					if name, ok := config["name"]; ok {
+						// Both `name` and `dbName` are set, so error
+						if _, ok := config["dbName"]; ok {
+							return nil, fmt.Errorf("Cannot specify both name and dbName, " +
+								"please set only dbName")
+						}
+						// Name doesn't actually exist on the underlying provider anymore,
```
Comment (t0yv0) [inline provider/resources.go:2869]: Question, don't we need to emit a deprecation warning here where we do `config["dbName"] = name`? Or something else will emit a deprecation warning anyway?

File: provider/resources.go (hunk 1 above)
Comment (iwahbe) [reply provider/resources.go:7138]: If there is a callback, we give re-assign `prov.Resources[key].PreCheckCallback` so both the old callback and `applyTags` are called. Otherwise we just set `applyTags`.

If we introduce a new callback where we don't want this to happen, we can change this code. I don't expect that we will though.

File: provider/cmd/pulumi-resource-aws/schema.json [hunk 3]
```diff
@@ -261784,7 +261784,7 @@
                     },
                     "name": {
                         "type": "string",
-                        "willReplaceOnChanges": true
+                        "deprecationMessage": "This property has been deprecated. Please use 'dbName' instead."
```
Comment (t0yv0) [inline provider/cmd/pulumi-resource-aws/schema.json:261787]: I think as written it will still replace on changes, no? Because you copy the value into dbName which does replace on changes. Can we get "willREplaceOnChanges" marker back? I know it's only for docs.

File: sdk/dotnet/Rds/Instance.cs [hunk 4]
```diff
@@ -489,7 +489,7 @@ public partial class Instance : global::Pulumi.CustomResource
         public Output<bool> MultiAz { get; private set; } = null!;
 
         [Output("name")]
-        public Output<string> Name { get; private set; } = null!;
+        public Output<string?> Name { get; private set; } = null!;
```
Comment (t0yv0) [inline sdk/dotnet/Rds/Instance.cs:492]: Interesting. Benign? This might be coming out of tfgen changes actually

File: provider/resources.go (hunk 2 above)
Comment (iwahbe) [reply provider/resources.go:2869]: We need to emit the warning, but we don't have a way to do so here. https://github.com/pulumi/pulumi-terraform-bridge/pull/1333 provides the logging context to `PreCheckCallback`. When that merges, we add this patch:

```patch
 provider/resources.go | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/provider/resources.go b/provider/resources.go
index 9706f52d0d..e44a569b3f 100644
--- a/provider/resources.go
+++ b/provider/resources.go
@@ -2866,6 +2866,8 @@ func Provider() *tfbridge.ProviderInfo {
 							return nil, fmt.Errorf("Cannot specify both name and dbName, " +
 								"please set only dbName")
 						}
+						tfbridge.GetLogger(ctx).Warn("The `name` property is deprecated, " +
+							"please use `dbName` instead")
 						// Name doesn't actually exist on the underlying provider anymore,
 						// so we make sure it only sees `dbName`, not `name`.
 						config["dbName"] = name
```

File: upstream-patches/0015-Un-deprecate-RDS-instance-name.patch [hunk 5]
```diff
@@ -1,33 +0,0 @@
...
-
-diff --git a/internal/service/rds/instance.go b/internal/service/rds/instance.go
-index 45afa19e7f..cdecabe089 100644
---- a/internal/service/rds/instance.go
-+++ b/internal/service/rds/instance.go
-@@ -408,6 +408,16 @@ func ResourceInstance() *schema.Resource {
- 				Optional: true,
- 				Computed: true,
- 			},
-+			"name": {
```
Comment (t0yv0) [inline upstream-patches/0015-Un-deprecate-RDS-instance-name.patch:21]: Yes! Here we go, delete this one.

File: provider/cmd/pulumi-resource-aws/schema.json (hunk 3 above)
Comment (iwahbe) [reply provider/cmd/pulumi-resource-aws/schema.json:261787]: It will. I'll add that message back in.

File: sdk/dotnet/Rds/Instance.cs (hunk 4 above)
Comment (iwahbe) [reply sdk/dotnet/Rds/Instance.cs:492]: This is real and correct. `name` is not set if the user correctly supplies `dbName`.

File: provider/resources.go (hunk 2 above)
Comment (t0yv0) [reply provider/resources.go:2870]: Well you can send a warning to glog  or even printf "WARNING" that should work already AFAIK, even if not ideal (not tied to the resource). 

How does the experience look like right now? We need this for go/no-go.

https://github.com/pulumi/pulumi-terraform-bridge/pull/1333 needs tests and some iteration it seems like, trying to weight in if we have enough time to land that first.

File: provider/resources.go (hunk 1 above)
Comment (guineveresaenger) [reply provider/resources.go:7139]: > If there is a callback, we give re-assign prov.Resources[key].PreCheckCallback so both the old callback and applyTags are called. Otherwise we just set applyTags.

Makes sense!

> If we introduce a new callback where we don't want this to happen, we can change this code. I don't expect that we will though.
How will a future maintainer know to change this code? 
If we don't expect new callbacks to be introduced - should we use the resource name as an explicit trigger here?

Comment (iwahbe) [reply provider/resources.go:7139]: > How will a future maintainer know to change this code?

If a future maintainer wants to add a new `PreCheckCallback` to a specific resource that overrides the behavior of tags, they will notice their change is not working and investigate. It's all in this file. They can grep for `PreCheckCallback` in `resources.go` and find this.

> If we don't expect new callbacks to be introduced - should we use the resource name as an explicit trigger here?

I'm not sure what you mean? Can you elaborate?

Comment (guineveresaenger) [reply provider/resources.go:7140]: > they will notice their change is not working and investigate.
I don't think that is ideal. I think the design of PreCheckCallback invites one to think "oh neat, I can add a callback in this place, on a resource". Getting a surprise can be really frustrating, regardless of how easy it would be to grep for PreCheckCallback.

> Can you elaborate?
If this particular callback is unique to `rds.Instance`, I think I would prefer logic that explicitly triggers on "if this resource is `rds.Instance`, use this callback". That will avoid a future maintainer having to look why something seemingly unrelated is getting involved with their callback.

I guess my TL;DR is: I don't think that "PreCheckCallback is not nil" is a discerning enough evaluation to decide whether we should call this code. Let's just use `rds.Instance`. After all, we would want to _remove_ this on v7, correct?

**Comment by fruttu** [comment]
Hello, I noticed this PR as we are facing issues when upgrading from version 5.42.0 to 6.2.0 with Python.

Firstly, this warning is probably incorrect:
```warning: name is deprecated: This property has been deprecated. Please use 'dbName' instead.```

As there is no 'dbName' property here: https://github.com/pulumi/pulumi-aws/blob/master/sdk/python/pulumi_aws/rds/instance.py#L19-L81

Pulumi is also attempting to execute a replacement of the ```aws.rds.Instance``` in our case. This is probably not as intended?

When using the deprecated **name** property,Pulumi preview shows:
```aws:rds:Instance   **-*****-***   replace   [diff: +dbName]; 2 warnings``` 

If we change the **name** property to **db_name**, Pulumi preview displays:
```aws:rds:Instance   **-*****-***   replace   [diff: +dbName]```

If we don't set properties **name** or **db_name** Pulumi preview runs without any changes (update/replace) to the RDS instance.
