### PR TITLE
Fix eventBus support in EventRule#onEvent

### LINKED ISSUE #1323: CloudWatch EventRule onEvent does not use eventBusName
When specifying the `eventBusName` on an `EventRule`, the `onEvent` seems to just use the `default` event bus.

```typescript
import * as aws from "@pulumi/aws";

const eventBusHealth = new aws.cloudwatch.EventBus("health");

const ec2IssueEventRule = new aws.cloudwatch.EventRule("ec2-issue", {
  description: "Trigger Lambda to respond to EC2 issue events",
  eventPattern: JSON.stringify({
    source: ["aws.health"],
    "detail-type": ["AWS Health Event"],
    detail: {
      service: ["EC2"],
      eventTypeCategory: ["issue"],
    },
  }),
  eventBusName: eventBusHealth.name,
});

ec2IssueEventRule.onEvent("ec2-issue", (event) => {
  console.log(event);
});
```

This results an error since the rule doesn't exist on the default bus.

```
  aws:cloudwatch:EventTarget (ec2-issue):
    error: 1 error occurred:
        * Creating CloudWatch Events Target failed: ResourceNotFoundException: Rule ec2-issue-3bc3cfa does not exist on EventBus default.
```

### PR DESCRIPTION
**Pull request by lukehoban**
In cases where the EventRule specified an eventBus other than `default`, this was not being used correctly in the EventTarget.  We can just pass along the eventBusName from the rule to the target.

Fixes #1323.

### CODE REVIEW

File: sdk/nodejs/cloudwatch/eventRuleMixins.ts [hunk 1]
```diff
@@ -107,6 +107,7 @@ export class EventRuleEventSubscription extends lambda.EventSubscription {
             rule: this.eventRule.name,
             arn: this.func.arn,
             targetId: name,
+            eventBusName: this.eventRule.eventBusName.apply(x => x!),
```
Comment (Zaid-Ajaj) [inline sdk/nodejs/cloudwatch/eventRuleMixins.ts:110]: is it possible that `this.eventRule.eventBusName` can be undefined? When constructing an `EventRule`, `eventBusName` is an [optional input](https://github.com/pulumi/pulumi-aws/blob/master/sdk/nodejs/cloudwatch/eventRule.ts#L234), the docs does say that it takes `default` event bus when omitted but I am not sure if that makes sure that `eventBusName` is always populated. 

In case `this.eventRule.eventBusName` can be undefined:
```js
eventBusName: this.eventRule.eventBusName == undefined 
  ? undefined
  : this.eventRule.eventBusName.apply(x => x!),
```
LGTM otherwise

**Review by Zaid-Ajaj — APPROVED** [review]

File: sdk/nodejs/cloudwatch/eventRuleMixins.ts (hunk 1 above)
Comment (lukehoban) [reply sdk/nodejs/cloudwatch/eventRuleMixins.ts:110]: It is possible it is undefined, and if it is, this code will result in passing that undefined value through into the outer `eventBusName` property, which is correct.

Unfortunately, our TypeScript typing of optional inputs is "wrong" per https://github.com/pulumi/pulumi/issues/6175 (with a proposed fix in https://github.com/pulumi/pulumi/pull/6323 that has likely bitrotted).  This code I added here works around that "wrong"-ness, while still behaving correctly.

The code you suggested unfortunately won't work - because `this.eventRule.eventBusName` itself is not undefined, it is an `Output<undefined>`.  It is the value inside the Output which might be undefined.

Comment (Zaid-Ajaj) [reply sdk/nodejs/cloudwatch/eventRuleMixins.ts:110]: Aah I see, thanks for explaining the context behind this! 

> The code you suggested unfortunately won't work

Yeah I was assuming the outer output itself could be undefined but it seems that only the data underneath could be that.
