### PR TITLE
[v7]: Remove remaining dangling schema references

### LINKED ISSUE #2565: Invalid references in Pulumi package schema
@davidspielmann and I recently started looking deeper into Pulumi package schemas and bumped into some issues with named types/references in the schema of the aws classic provider. Talking about it at PulumiUP, @mnlumi encouraged us to share our insight. Perhaps it can help to get some of the references fixed with the upcoming 6.0 release :)

Background: Pulumi package schemas include "Named Types", which are references (a URI string) to a type specification. Our understanding of how these URIs are resolved from the `$ref` field is https://github.com/pulumi/pulumi/blob/master/pkg/codegen/schema/schema.go#L1409-L1416
Valid references are the built-in types `pulumi.json#/Archive`, `pulumi.json#/Asset`, `pulumi.json#/Any`, and `pulumi.json#/Json`. All other references have the format `[origin]#/{resources,types}/[urn]` where [origin] is the file path or URL of a schema file (empty for in-document references) and [urn] the identifier of the respective type definition under "resources" or "types" in that schema. 

Expectation: All references in a package schema can be resolved. However, 168 references (25 URIs) in the schema of aws@5.41.0 cannot be resolved as defined above. These are the non-resolvable URIs we found; some of them are also noted in other GH issues (referenced).

These 77 references (15 URIs) cannot be resolved but are valid resources, i.e., they could be resolved when prefixing with `#/resources/`:

* `aws:apigateway/deployment:Deployment` (2 occurrences)
* `aws:apigateway/restApi:RestApi` (24 occurrences)
* `aws:cloudwatch/logGroup:LogGroup` (2 occurrences)
* `aws:ec2/launchConfiguration:LaunchConfiguration` (2 occurrences)
* `aws:ec2/placementGroup:PlacementGroup` (2 occurrences)
* `aws:elasticbeanstalk/application:Application` (4 occurrences)
* `aws:elasticbeanstalk/applicationVersion:ApplicationVersion` (3 occurrences) https://github.com/pulumi/pulumi-aws/issues/2358
* `aws:iam/group:Group` (4 occurrences)
* `aws:iam/instanceProfile:InstanceProfile` (4 occurrences)
* `aws:iam/role:Role` (8 occurrences) https://github.com/pulumi/pulumi-aws/issues/1820
* `aws:iam/user:User` (4 occurrences)
* `aws:iot/policy:Policy` (2 occurrences)
* `aws:lambda/function:Function` (2 occurrences)
* `aws:s3/bucket:Bucket` (6 occurrences)
* `aws:sns/topic:Topic` (8 occurrences)

These 21 references (5 URIs) cannot be resolved but are valid types if treated case-insensitive, i.e., they could be resolved when ignoring the case and prefixing with `#/types/`:

* `aws:alb/ipAddressType:IpAddressType` (6 occurrences) https://github.com/pulumi/pulumi-aws/issues/2362
* `aws:alb/loadBalancerType:LoadBalancerType` (6 occurrences) https://github.com/pulumi/pulumi-aws/issues/2362
* `aws:autoscaling/notificationType:NotificationType` (3 occurrences)
* `aws:index/region:Region` (3 occurrences) https://github.com/pulumi/pulumi-aws/issues/2463
* `aws:rds/engineType:EngineType` (3 occurrences)

These 70 references (5 URIs) cannot be resolved and we did not find a way to fix it:

* `aws:autoscaling/metrics:Metric` (3 occurrences)
* `aws:ecr/lifecyclePolicyDocument:LifecyclePolicyDocument` (2 occurrences)
* `aws:iam/documents:PolicyDocument` (22 occurrences)
* `aws:index/aRN:ARN` (42 occurrences)  https://github.com/pulumi/pulumi-aws/issues/1682
* `aws:s3/routingRules:RoutingRule` (1 occurrences)

This is the Python notebook we used for this analysis. It also applies the analyis to aws-native@0.65.0, akamai@4.4.0, alicloud@3.38.0, azure@5.44.0, azure-native@1.103.0, azure-native@v2.0.0-beta.1, cloudflare@5.3.0, gcp@6.58.0, google-native@0.30.0, hcloud@1.12.1, kubernetes@3.29.1, random@4.13.2. For most of them, all references are fine, with minimal exceptions (which, ideally, also would be fixed).
https://gist.github.com/DSoko2/4630a14c97a9469385dceed0ab07bc1f

We hope this helps to improve this provider's schema, i.e, eliminate workarounds and non-resolvable URIs. If you should have questions or we can help somehow, please let us know.

### LINKED ISSUE #5250: Remove dangling references from schema
### Describe what happened

In https://github.com/pulumi/pulumi-aws/issues/2565 we looked at making the schema conforming to checks by removing dangling references. Unfortunately due to legacy overlays this change is breaking. And as a workaround a "minimal schema" is made available that does not model these overlays but is otherwise conformant. This ticket is a reminder that at the next major version of the provider we should clean this up and take the breaking changes so there is only one schema and it is the good done.

### Sample program

N/A

### Log output

N/A

### Affected Resource(s)

N/A

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by corymhall**
This PR removes the remaining dangling references.

- `EngineType` had the wrong casing (fixed)
- `LifecyclePolicyDocument` similar to #5565 this converts the overlay types to schema types

The stacked PR #5583 follows this up by completely removing all the minimal schema stuff and adds validation that there are no dangling references.

fixes #5250, fixes #2565

### CODE REVIEW

**Comment by corymhall** [comment]
This change is part of the following stack:

- #5582 ◀
    - #5583

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

**Review by mjeffryes — APPROVED** [review]
Nice. ~Will we eventually get rid of pkg/minimalschema entirely?~ I see this is handled in the second PR!

File: sdk/nodejs/rds/globalCluster.ts [hunk 1]
```diff
@@ -54,7 +54,7 @@ import * as utilities from "../utilities";
  *     dependsOn: [primaryClusterInstance],
  * });
  * const secondaryClusterInstance = new aws.rds.ClusterInstance("secondary", {
- *     engine: example.engine,
+ *     engine: example.engine.apply((x) => aws.rds.EngineType[x]),
```
Comment (t0yv0) [inline sdk/nodejs/rds/globalCluster.ts:57]: Does this look right? Interesting.

**Review by t0yv0 — APPROVED** [review]
Looking good at a glance.
